[package]
name = "espspect"
version = "0.5.0"
edition = "2024"

[[bin]]
name = "espspect"
harness = false # do not use the built-in cargo test harness -> resolve rust-analyzer errors

[profile.release]
codegen-units = 1
debug = 0
lto = "fat"
opt-level = "s"

[profile.dev]
debug = true    # Symbols are nice, and they don't increase the size on Flash
lto = "fat"
opt-level = "s"

[dependencies]
esp-idf-svc = "0.52"
rtrb = "0.4"
microfft = { version = "0.6", default-features = false, features = ["size-1024"] }
gamma-table-macros = "0.1"

[build-dependencies]
embuild = "0.33"